package entity;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;

/**
 * MenuItem generated by hbm2java
 */
@Entity
@Table(name = "MENU_ITEM", schema = "PUBLIC", catalog = "PUBLIC")
public class MenuItem implements java.io.Serializable {

    private String guid;
    private Date createTime;
    private Boolean isSoldout;
    private Integer itemCost;
    private String itemDescription;
    private String itemMemo;
    private String itemName;
    private Integer itemPrice;
    private String itemSName;
    private Integer itemType;

    public MenuItem() {
    }

    public MenuItem(String guid) {
        this.guid = guid;
    }

    public MenuItem(String guid, Date createTime, Boolean isSoldout, Integer itemCost, String itemDescription, String itemMemo, String itemName, Integer itemPrice, String itemSName, Integer itemType) {
        this.guid = guid;
        this.createTime = createTime;
        this.isSoldout = isSoldout;
        this.itemCost = itemCost;
        this.itemDescription = itemDescription;
        this.itemMemo = itemMemo;
        this.itemName = itemName;
        this.itemPrice = itemPrice;
        this.itemSName = itemSName;
        this.itemType = itemType;
    }

    @Id
    @Column(name = "GUID", unique = true, nullable = false, length = 50)
    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "IS_SOLDOUT")
    public Boolean getIsSoldout() {
        return this.isSoldout;
    }

    public void setIsSoldout(Boolean isSoldout) {
        this.isSoldout = isSoldout;
    }

    @Column(name = "ITEM_COST")
    public Integer getItemCost() {
        return this.itemCost;
    }

    public void setItemCost(Integer itemCost) {
        this.itemCost = itemCost;
    }

    @Column(name = "ITEM_DESCRIPTION", length = 200)
    public String getItemDescription() {
        return this.itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    @Column(name = "ITEM_MEMO", length = 200)
    public String getItemMemo() {
        return this.itemMemo;
    }

    public void setItemMemo(String itemMemo) {
        this.itemMemo = itemMemo;
    }

    @Column(name = "ITEM_NAME", length = 200)
    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Column(name = "ITEM_PRICE")
    public Integer getItemPrice() {
        return this.itemPrice;
    }

    public void setItemPrice(Integer itemPrice) {
        this.itemPrice = itemPrice;
    }

    @Column(name = "ITEM_S_NAME", length = 50)
    public String getItemSName() {
        return this.itemSName;
    }

    public void setItemSName(String itemSName) {
        this.itemSName = itemSName;
    }

    @Column(name = "ITEM_TYPE")
    public Integer getItemType() {
        return this.itemType;
    }

    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

}
