package entity;
import java.util.Collection;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderCard generated by hbm2java
 */
@Entity
@Table(name = "ORDER_CARD", schema = "PUBLIC", catalog = "PUBLIC")
public class OrderCard implements java.io.Serializable {

    private String guid;
    private Boolean cardStatus;
    private Date createTime;
    private Date modifyTime;
    private Date orderTime;
    private Integer sumPrice;
    private Integer tableNum;
    private Collection<OrderCardDetail> orderCardDetails;

    public OrderCard() {
    }

    public OrderCard(String guid) {
        this.guid = guid;
    }

    public OrderCard(String guid, Boolean cardStatus, Date createTime, Date modifyTime, Date orderTime, Integer sumPrice, Integer tableNum) {
        this.guid = guid;
        this.cardStatus = cardStatus;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.orderTime = orderTime;
        this.sumPrice = sumPrice;
        this.tableNum = tableNum;
    }

    @Id
    @Column(name = "GUID", unique = true, nullable = false, length = 50)
    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    @Column(name = "CARD_STATUS")
    public Boolean getCardStatus() {
        return this.cardStatus;
    }

    public void setCardStatus(Boolean cardStatus) {
        this.cardStatus = cardStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MODIFY_TIME", length = 26)
    public Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ORDER_TIME", length = 10)
    public Date getOrderTime() {
        return this.orderTime;
    }

    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    @Column(name = "SUM_PRICE")
    public Integer getSumPrice() {
        return this.sumPrice;
    }

    public void setSumPrice(Integer sumPrice) {
        this.sumPrice = sumPrice;
    }

    @Column(name = "TABLE_NUM")
    public Integer getTableNum() {
        return this.tableNum;
    }

    public void setTableNum(Integer tableNum) {
        this.tableNum = tableNum;
    }

    @OneToMany(mappedBy="cardGuid",fetch = FetchType.EAGER, cascade=CascadeType.ALL, targetEntity=OrderCardDetail.class)
    public Collection<OrderCardDetail> getOrderCardDetails() {
        return orderCardDetails;
    }

    public void setOrderCardDetails(Collection<OrderCardDetail> orderCardDetails) {
        this.orderCardDetails = orderCardDetails;
    }
    
}
