package entity;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;

/**
 * OrderCardDetail generated by hbm2java
 */
@Entity
@Table(name = "ORDER_CARD_DETAIL", schema = "PUBLIC", catalog = "PUBLIC")
public class OrderCardDetail implements java.io.Serializable {

    private String guid;
    private String cardGuid;
    private Date createTime;
    private String detailMemo;
    private String detailName;
    private Integer detailNum;
    private Integer detailPrice;
    private Boolean isOut;
    private String itemGuid;

    public OrderCardDetail() {
    }

    public OrderCardDetail(String guid, String cardGuid, String itemGuid) {
        this.guid = guid;
        this.cardGuid = cardGuid;
        this.itemGuid = itemGuid;
    }

    public OrderCardDetail(String guid, String cardGuid, Date createTime, String detailMemo, String detailName, Integer detailNum, Integer detailPrice, Boolean isOut, String itemGuid) {
        this.guid = guid;
        this.cardGuid = cardGuid;
        this.createTime = createTime;
        this.detailMemo = detailMemo;
        this.detailName = detailName;
        this.detailNum = detailNum;
        this.detailPrice = detailPrice;
        this.isOut = isOut;
        this.itemGuid = itemGuid;
    }

    @Id
    @Column(name = "GUID", unique = true, nullable = false, length = 50)
    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    @Column(name = "CARD_GUID", nullable = false, length = 50)
    public String getCardGuid() {
        return this.cardGuid;
    }

    public void setCardGuid(String cardGuid) {
        this.cardGuid = cardGuid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "DETAIL_MEMO", length = 200)
    public String getDetailMemo() {
        return this.detailMemo;
    }

    public void setDetailMemo(String detailMemo) {
        this.detailMemo = detailMemo;
    }

    @Column(name = "DETAIL_NAME", length = 200)
    public String getDetailName() {
        return this.detailName;
    }

    public void setDetailName(String detailName) {
        this.detailName = detailName;
    }

    @Column(name = "DETAIL_NUM")
    public Integer getDetailNum() {
        return this.detailNum;
    }

    public void setDetailNum(Integer detailNum) {
        this.detailNum = detailNum;
    }

    @Column(name = "DETAIL_PRICE")
    public Integer getDetailPrice() {
        return this.detailPrice;
    }

    public void setDetailPrice(Integer detailPrice) {
        this.detailPrice = detailPrice;
    }

    @Column(name = "IS_OUT")
    public Boolean getIsOut() {
        return this.isOut;
    }

    public void setIsOut(Boolean isOut) {
        this.isOut = isOut;
    }

    @Column(name = "ITEM_GUID", nullable = false, length = 50)
    public String getItemGuid() {
        return this.itemGuid;
    }

    public void setItemGuid(String itemGuid) {
        this.itemGuid = itemGuid;
    }
    
    
}
